controller_list:
  - name: fake_arm_controller
    joints:
      - robot_joint1
      - robot_joint2
      - robot_joint3
      - robot_joint4
      - robot_joint5
      - robot_joint6
  - name: fake_gripper_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: home