# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# joint_limits:
#   robot_joint1:
#     has_velocity_limits: true
#     max_velocity: 0.3
#     has_acceleration_limits: false
#     max_acceleration: 0
#   robot_joint2:
#     has_velocity_limits: true
#     max_velocity: 4.147
#     has_acceleration_limits: false
#     max_acceleration: 0
#   robot_joint3:
#     has_velocity_limits: true
#     max_velocity: 3.665
#     has_acceleration_limits: false
#     max_acceleration: 0
#   robot_joint4:
#     has_velocity_limits: true
#     max_velocity: 4.974
#     has_acceleration_limits: false
#     max_acceleration: 0
#   robot_joint5:
#     has_velocity_limits: true
#     max_velocity: 1.623
#     has_acceleration_limits: false
#     max_acceleration: 0
#   robot_joint6:
#     has_velocity_limits: true
#     max_velocity: 3.665
#     has_acceleration_limits: false
#     max_acceleration: 0

joint_limits:
  robot_joint1:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 0.1
  robot_joint2:
    has_velocity_limits: true
    max_velocity: 4.147
    has_acceleration_limits: true
    max_acceleration: 2.055
  robot_joint3:
    has_velocity_limits: true
    max_velocity: 3.665
    has_acceleration_limits: true
    max_acceleration: 1.83
  robot_joint4:
    has_velocity_limits: true
    max_velocity: 4.974
    has_acceleration_limits: true
    max_acceleration: 2.45
  robot_joint5:
    has_velocity_limits: true
    max_velocity: 1.623
    has_acceleration_limits: true
    max_acceleration: 0.81
  robot_joint6:
    has_velocity_limits: true
    max_velocity: 3.665
    has_acceleration_limits: true
    max_acceleration: 1.8