# arm:
#   kinematics_solver: robot_arm/IKFastKinematicsPlugin
#   kinematics_solver_attemps: 5
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.05

arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05